### PR TITLE
Create v13-beta.tweet

### PR DESCRIPTION
**Pull request by gr2m**
Let's see if this thing is still working 🤣

### CODE REVIEW

**Review by wolfy1339 — APPROVED** [review]

**Review by Uzlopak — APPROVED** [review]
LGTM

**Comment by Uzlopak** [comment]
@gr2m 

Can we first merge smee-client into the beta before we encourage beta testing?

**Comment by gr2m** [comment]
> Can we first merge smee-client into the beta before we encourage beta testing?

sure let's do that

**Comment by Uzlopak** [comment]
@gr2m 
lets merge it

**Comment by gr2m** [comment]
auto-tweeting failed. I tweeted manually: https://twitter.com/ProbotTheRobot/status/1727003620384948254

<blockquote><div>X (formerly Twitter)</div></blockquote>

**Pull request merged**
